/** Researched issuer rates, August 2026. Not a balance tracker — swipe picker data. */

export const RATES_AS_OF = "August 2026";
export const CATALOG_VERSION = "2026-08";

export const HOTEL_BRANDS = new Set(["hilton", "marriott", "hyatt", "ihg", "wyndham", "choice"]);

export const QUARTERLY_CALENDAR = {
  2026: {
    1: {
      discover: ["groceries", "wholesale", "streaming"],
    },
    2: {
      discover: ["dining", "home"],
    },
    3: {
      chase: ["gas", "ev", "transit", "entertainment"],
      discover: ["gas", "transit", "drugstores"],
      citiDividend: ["gas", "home"],
    },
    4: {},
  },
};

export const CATEGORIES = [
  { id: "dining", label: "Dining", icon: "🍽️", modes: ["everyday", "travel", "business"] },
  { id: "groceries", label: "Groceries", icon: "🛒", modes: ["everyday"] },
  { id: "gas", label: "Gas", icon: "⛽", modes: ["everyday", "business"] },
  { id: "ev", label: "EV", icon: "🔌", modes: ["everyday", "travel"] },
  { id: "amazon", label: "Amazon", icon: "📦", modes: ["everyday"] },
  { id: "target", label: "Target", icon: "🎯", modes: ["everyday"] },
  { id: "walmart", label: "Walmart", icon: "🏪", modes: ["everyday"] },
  { id: "costco", label: "Costco", icon: "🧾", modes: ["everyday"] },
  { id: "wholesale", label: "Wholesale", icon: "📦", modes: ["everyday", "business"] },
  { id: "drugstores", label: "Drugstore", icon: "💊", modes: ["everyday"] },
  { id: "streaming", label: "Streaming", icon: "📺", modes: ["everyday"] },
  { id: "utilities", label: "Utilities", icon: "💡", modes: ["everyday"] },
  { id: "rent", label: "Rent", icon: "🏠", modes: ["everyday"] },
  { id: "electronics", label: "Electronics", icon: "💻", modes: ["everyday", "business"] },
  { id: "apple", label: "Apple", icon: "", modes: ["everyday"] },
  { id: "home", label: "Home", icon: "🔨", modes: ["everyday"] },
  { id: "entertainment", label: "Events", icon: "🎟️", modes: ["everyday", "travel"] },
  { id: "other", label: "Other", icon: "💳", modes: ["everyday"] },
  { id: "flights", label: "Flights", icon: "✈️", modes: ["travel"] },
  { id: "hotels", label: "Hotels", icon: "🏨", modes: ["travel"] },
  { id: "car_rental", label: "Cars", icon: "🚗", modes: ["travel"] },
  { id: "transit", label: "Transit", icon: "🚇", modes: ["everyday", "travel", "business"] },
  { id: "travel", label: "Travel", icon: "🧳", modes: ["travel"] },
  { id: "overseas", label: "Overseas", icon: "🌍", modes: ["travel"] },
  { id: "office", label: "Office", icon: "📎", modes: ["business"] },
  { id: "shipping", label: "Shipping", icon: "📫", modes: ["business"] },
  { id: "ads", label: "Ads", icon: "📣", modes: ["business"] },
  { id: "software", label: "Software", icon: "☁️", modes: ["business"] },
  { id: "wireless", label: "Wireless", icon: "📱", modes: ["business", "everyday"] },
  { id: "internet", label: "Internet", icon: "🌐", modes: ["business", "everyday"] },
  { id: "phone", label: "Phone", icon: "☎️", modes: ["business"] },
];

export const MERCHANTS = {
  amazon: { label: "Amazon", category: "amazon", aliases: ["amazon.com", "amzn", "amazon fresh"] },
  "whole-foods": { label: "Whole Foods", category: "groceries", aliases: ["whole foods", "wholefoods"] },
  target: { label: "Target", category: "target", aliases: ["target.com"] },
  costco: { label: "Costco", category: "costco", requiredNetwork: "visa", aliases: ["costco.com", "costco wholesale"] },
  "costco-gas": { label: "Costco Gas", category: "gas", requiredNetwork: "visa", aliases: ["costco fuel"] },
  walmart: { label: "Walmart", category: "walmart", aliases: ["walmart.com"] },
  staples: { label: "Staples", category: "office", aliases: ["staples.com"] },
  "office-depot": { label: "Office Depot", category: "office", aliases: ["office depot", "officedepot", "office max"] },
  hilton: { label: "Hilton", category: "hotels", aliases: ["hilton honors", "hampton", "doubletree", "embassy suites", "waldorf", "conrad"] },
  marriott: { label: "Marriott", category: "hotels", aliases: ["bonvoy", "westin", "sheraton", "ritz", "w hotel"] },
  hyatt: { label: "Hyatt", category: "hotels", aliases: ["world of hyatt"] },
  ihg: { label: "IHG", category: "hotels", aliases: ["holiday inn", "intercontinental", "kimpton"] },
  "best-buy": { label: "Best Buy", category: "electronics", aliases: ["best buy", "bestbuy"] },
  apple: { label: "Apple", category: "apple", aliases: ["apple store", "apple.com"] },
  "home-depot": { label: "Home Depot", category: "home", aliases: ["home depot", "homedepot"] },
  lowes: { label: "Lowe's", category: "home", aliases: ["lowe's", "lowes"] },
  uber: { label: "Uber", category: "transit", aliases: ["uber eats"] },
  lyft: { label: "Lyft", category: "transit", aliases: [] },
  delta: { label: "Delta", category: "flights", aliases: ["delta.com"] },
  united: { label: "United", category: "flights", aliases: ["united.com"] },
  southwest: { label: "Southwest", category: "flights", aliases: ["southwest.com"] },
  jetblue: { label: "JetBlue", category: "flights", aliases: [] },
  "american-airlines": { label: "American Airlines", category: "flights", aliases: ["aa.com", "american airlines"] },
  verizon: { label: "Verizon", category: "wireless", aliases: [] },
  att: { label: "AT&T", category: "wireless", aliases: ["at&t"] },
  tmobile: { label: "T-Mobile", category: "wireless", aliases: ["t-mobile"] },
  fedex: { label: "FedEx", category: "shipping", aliases: [] },
  ups: { label: "UPS", category: "shipping", aliases: [] },
  usps: { label: "USPS", category: "shipping", aliases: [] },
  google: { label: "Google Ads", category: "ads", aliases: ["google ads"] },
  meta: { label: "Meta Ads", category: "ads", aliases: ["facebook ads", "instagram ads"] },
  adobe: { label: "Adobe", category: "software", aliases: [] },
  microsoft: { label: "Microsoft", category: "software", aliases: [] },
  "sams-club": { label: "Sam's Club", category: "wholesale", aliases: ["sams club"] },
  cvs: { label: "CVS", category: "drugstores", aliases: [] },
  walgreens: { label: "Walgreens", category: "drugstores", aliases: [] },
};

function c(p) {
  return {
    annualFee: p.fee ?? 0,
    flags: p.flags || [],
    aliases: p.aliases || [],
    cpp: p.cpp ?? 1,
    currency: p.cur || "cash",
    base: p.base ?? 1,
    rates: p.rates || {},
    merchants: p.merchants || {},
    perks: p.perks || [],
    dedicated: p.dedicated || [],
    specialist: p.specialist || [],
    cobrand: p.cobrand || null,
    cobrandRate: p.cobrandRate || null,
    kind: p.kind || "personal",
    network: p.network || "visa",
    rotating: p.rotating || null,
    rotatingCategories: p.rotatingCategories || null,
    focusDefault: p.focusDefault || null,
    focusCount: p.focusCount || 0,
    focusRate: p.focusRate || 4,
    focusCap: p.focusCap || 150000,
    rentEligible: Boolean(p.rentEligible),
    color: p.color || "#888",
    issuer: p.issuer,
    name: p.name,
    short: p.short || p.name,
    id: p.id,
    notes: p.notes || "",
  };
}

export const CARDS = [
  c({
    id: "amex-gold",
    name: "Amex Gold (Personal)",
    short: "Gold",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 325,
    flags: ["no_fx_fee"],
    aliases: ["rose gold", "amex rose gold", "personal gold", "gold card", "the gold card"],
    cpp: 2,
    cur: "MR",
    color: "#c4a35a",
    rates: { dining: 4, groceries: { rate: 4, cap: 25000 }, flights: 3 },
    perks: ["warranty", "purchase_protection"],
    specialist: ["dining", "groceries"],
    notes: "4x restaurants worldwide (first $50k/year), 4x U.S. supermarkets (first $25k), 3x flights booked direct or Amex Travel. No foreign transaction fee.",
  }),
  c({
    id: "amex-platinum",
    name: "Amex Platinum",
    short: "Platinum",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 695,
    flags: ["no_fx_fee"],
    aliases: ["personal platinum", "plat"],
    cpp: 2,
    cur: "MR",
    color: "#d9d9d9",
    rates: { flights: 5, hotels: 5, travel: 5 },
    perks: ["warranty", "purchase_protection", "lounge"],
    specialist: ["flights"],
    notes: "5x flights booked direct or Amex Travel, 5x prepaid hotels on Amex Travel. No FX fee.",
  }),
  c({
    id: "amex-green",
    name: "Amex Green",
    short: "Green",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1.8,
    cur: "MR",
    color: "#2e6b4f",
    rates: { travel: 3, transit: 3, dining: 3 },
    perks: ["warranty"],
    specialist: ["transit"],
  }),
  c({
    id: "amex-blue-cash-preferred",
    name: "Blue Cash Preferred",
    short: "BCP",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 95,
    cpp: 1,
    cur: "cash",
    color: "#1e4e8c",
    rates: { groceries: { rate: 6, cap: 6000 }, streaming: 6, transit: 3, gas: 3 },
    specialist: ["groceries"],
  }),
  c({
    id: "amex-blue-cash-everyday",
    name: "Blue Cash Everyday",
    short: "BCE",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#3d7cc9",
    rates: { groceries: { rate: 3, cap: 6000 }, gas: { rate: 3, cap: 6000 }, online: 3, home: { rate: 3, cap: 6000 } },
  }),
  c({
    id: "amex-everyday",
    name: "Amex EveryDay",
    short: "EveryDay",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1.6,
    cur: "MR",
    color: "#7aa2d6",
    rates: { groceries: 2 },
    notes: "20% extra points when you use the card 20+ times in a billing period.",
  }),
  c({
    id: "amex-everyday-preferred",
    name: "Amex EveryDay Preferred",
    short: "EDP",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 95,
    cpp: 1.6,
    cur: "MR",
    color: "#5b82b8",
    rates: { groceries: 3 },
  }),
  c({
    id: "amex-cash-magnet",
    name: "Amex Cash Magnet",
    short: "Cash Magnet",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#6b6b6b",
    base: 1.5,
  }),
  c({
    id: "amex-business-gold",
    name: "Amex Business Gold",
    short: "Biz Gold",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 375,
    flags: ["no_fx_fee"],
    aliases: ["business gold", "amex biz gold"],
    cpp: 2,
    cur: "MR",
    color: "#b8860b",
    rates: { flights: 3, hotels: 3 },
    perks: ["warranty", "purchase_protection"],
    rotatingCategories: ["ads", "electronics", "dining", "gas", "transit", "wireless"],
    focusDefault: ["electronics", "ads"],
    focusCount: 2,
    focusRate: 4,
    focusCap: 150000,
    notes: "4x on the two chosen/top categories each cycle from ads, electronics/software, dining, gas, transit, wireless. Default focus: electronics + ads. $150k combined cap. No FX fee. Dining is 1x unless it is one of the two chosen categories.",
  }),
  c({
    id: "amex-business-platinum",
    name: "Amex Business Platinum",
    short: "Biz Plat",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 695,
    flags: ["no_fx_fee"],
    cpp: 2,
    cur: "MR",
    color: "#c0c0c0",
    rates: { flights: 5, hotels: 5, electronics: 1.5 },
    perks: ["warranty", "purchase_protection", "lounge"],
    specialist: ["flights"],
    notes: "5x flights and prepaid hotels on Amex Travel; select electronics retailers sometimes 1.5x. No FX fee.",
  }),
  c({
    id: "amex-business-green",
    name: "Amex Business Green",
    short: "Biz Green",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 95,
    flags: [],
    cpp: 1.5,
    cur: "MR",
    color: "#1f5c40",
    rates: { travel: 2 },
    notes: "Has a 2.7% foreign transaction fee. Do not treat as no-FX.",
  }),
  c({
    id: "amex-blue-business-plus",
    name: "Blue Business Plus",
    short: "BBP",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 0,
    flags: [],
    cpp: 1.8,
    cur: "MR",
    color: "#2a62a8",
    rates: {},
    base: 2,
    notes: "2x MR on first $50k/year, then 1x. 2.7% foreign transaction fee.",
  }),
  c({
    id: "amex-blue-business-cash",
    name: "Blue Business Cash",
    short: "BBC",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 0,
    flags: [],
    cpp: 1,
    cur: "cash",
    color: "#3b6fad",
    base: 2,
    notes: "2% cash on first $50k/year. 2.7% foreign transaction fee.",
  }),
  c({
    id: "amex-amazon-business",
    name: "Amazon Business Amex",
    short: "Amazon Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#ff9900",
    merchants: { amazon: 3 },
    dedicated: ["amazon"],
    rates: { amazon: 3, other: 1 },
  }),
  c({
    id: "amex-amazon-business-prime",
    name: "Amazon Business Prime Amex",
    short: "Amazon Biz Prime",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#e47911",
    merchants: { amazon: 5 },
    dedicated: ["amazon"],
    notes: "5% Amazon Business with Prime. Still an Amex — Costco will not take it.",
  }),
  c({
    id: "amex-hilton-honors",
    name: "Hilton Honors Amex",
    short: "Hilton",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "Hilton",
    color: "#1a3c6e",
    cobrand: "hilton",
    cobrandRate: 7,
    merchants: { hilton: 7 },
    dedicated: ["hilton"],
    rates: { dining: 5, groceries: 5, gas: 5 },
  }),
  c({
    id: "amex-hilton-surpass",
    name: "Hilton Honors Surpass",
    short: "Surpass",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "Hilton",
    color: "#16325c",
    cobrand: "hilton",
    cobrandRate: 12,
    merchants: { hilton: 12 },
    dedicated: ["hilton"],
    specialist: ["hotels"],
    rates: { dining: 6, groceries: 6, gas: 6 },
  }),
  c({
    id: "amex-hilton-aspire",
    name: "Hilton Honors Aspire",
    short: "Aspire",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 550,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "Hilton",
    color: "#0f2748",
    cobrand: "hilton",
    cobrandRate: 14,
    merchants: { hilton: 14 },
    dedicated: ["hilton"],
    specialist: ["hotels"],
    rates: { flights: 7, car_rental: 7, dining: 7 },
    perks: ["lounge"],
  }),
  c({
    id: "amex-hilton-business",
    name: "Hilton Honors Business Amex",
    short: "Hilton Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 195,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "Hilton",
    color: "#1c3f73",
    cobrand: "hilton",
    cobrandRate: 12,
    merchants: { hilton: 12 },
    dedicated: ["hilton"],
    specialist: ["hotels"],
    rates: { dining: 6, gas: 6, office: 6 },
  }),
  c({
    id: "amex-marriott-bonvoy",
    name: "Marriott Bonvoy Amex",
    short: "Bonvoy Amex",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#8b1e3f",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
  }),
  c({
    id: "amex-marriott-bevy",
    name: "Marriott Bonvoy Bevy",
    short: "Bevy",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 250,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#6e1832",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
    rates: { dining: 4, groceries: 4 },
  }),
  c({
    id: "amex-marriott-brilliant",
    name: "Marriott Bonvoy Brilliant",
    short: "Brilliant",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 650,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#4a1022",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
    specialist: ["hotels"],
    rates: { dining: 3, travel: 3 },
  }),
  c({
    id: "amex-marriott-business",
    name: "Marriott Bonvoy Business Amex",
    short: "Bonvoy Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 125,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#7a1a38",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
  }),
  c({
    id: "amex-delta-blue",
    name: "Delta SkyMiles Blue",
    short: "Delta Blue",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1.15,
    cur: "Delta",
    color: "#003366",
    cobrand: "delta",
    merchants: { delta: 2 },
    rates: { dining: 2 },
  }),
  c({
    id: "amex-delta-gold",
    name: "Delta SkyMiles Gold",
    short: "Delta Gold",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#0a3d73",
    cobrand: "delta",
    merchants: { delta: 2 },
    rates: { dining: 2, groceries: 2 },
  }),
  c({
    id: "amex-delta-platinum",
    name: "Delta SkyMiles Platinum",
    short: "Delta Plat",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 350,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#0d4a8a",
    cobrand: "delta",
    merchants: { delta: 3 },
    rates: { dining: 3, groceries: 3 },
  }),
  c({
    id: "amex-delta-reserve",
    name: "Delta SkyMiles Reserve",
    short: "Delta Reserve",
    issuer: "American Express",
    network: "amex",
    kind: "personal",
    fee: 650,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#001f3d",
    cobrand: "delta",
    merchants: { delta: 3 },
    rates: { dining: 3 },
    perks: ["lounge"],
  }),
  c({
    id: "amex-delta-gold-biz",
    name: "Delta SkyMiles Gold Business",
    short: "Delta Gold Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#0a3d73",
    cobrand: "delta",
    merchants: { delta: 2 },
    rates: { dining: 2, gas: 2, office: 1.5 },
  }),
  c({
    id: "amex-delta-platinum-biz",
    name: "Delta SkyMiles Platinum Business",
    short: "Delta Plat Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 350,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#0d4a8a",
    cobrand: "delta",
    merchants: { delta: 3 },
    rates: { dining: 3 },
  }),
  c({
    id: "amex-delta-reserve-biz",
    name: "Delta SkyMiles Reserve Business",
    short: "Delta Reserve Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 650,
    flags: ["no_fx_fee"],
    cpp: 1.15,
    cur: "Delta",
    color: "#001f3d",
    cobrand: "delta",
    merchants: { delta: 3 },
    perks: ["lounge"],
  }),
  c({
    id: "amex-lowes-business",
    name: "Lowe's Business Rewards",
    short: "Lowe's Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0474bc",
    merchants: { lowes: 5 },
    dedicated: ["lowes"],
  }),
  c({
    id: "amex-plum",
    name: "Amex Plum Card",
    short: "Plum",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 250,
    cpp: 1,
    cur: "cash",
    color: "#6b3fa0",
    notes: "Early Pay Discount / deferred pay. Weak as a swipe rewards card.",
  }),
  c({
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred",
    short: "CSP",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.8,
    cur: "UR",
    color: "#1a3a6b",
    rates: { travel: 5, dining: 3, streaming: 3, groceries: 3, gas: 3, ev: 3 },
    specialist: ["dining", "travel"],
    notes: "5x Chase Travel; 3x dining, online groceries, streaming, gas/EV, vacation homes; 2x other travel.",
  }),
  c({
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve",
    short: "CSR",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 795,
    flags: ["no_fx_fee"],
    aliases: ["sapphire reserve", "csr"],
    cpp: 2,
    cur: "UR",
    color: "#0c1e3a",
    rates: { travel: 8, flights: 4, hotels: 4, dining: 3, transit: 5 },
    perks: ["lounge", "warranty"],
    specialist: ["dining", "travel", "flights", "hotels"],
    notes: "8x Chase Travel, 4x flights and hotels booked direct, 3x dining worldwide. $795 fee. No FX fee.",
  }),
  c({
    id: "chase-sapphire-reserve-business",
    name: "Chase Sapphire Reserve for Business",
    short: "CSR Biz",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 795,
    flags: ["no_fx_fee"],
    cpp: 2,
    cur: "UR",
    color: "#102544",
    rates: { travel: 8, flights: 4, hotels: 4, ads: 3 },
    specialist: ["ads", "travel"],
  }),
  c({
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited",
    short: "CFU",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1.5,
    cur: "UR",
    color: "#1177bb",
    base: 1.5,
    rates: { travel: 5, dining: 3, drugstores: 3 },
  }),
  c({
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex",
    short: "Flex",
    issuer: "Chase",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1.5,
    cur: "UR",
    color: "#0e6aa6",
    rates: { travel: 5, dining: 3, drugstores: 3 },
    rotating: { type: "quarterly", calendar: "chase", rate: 5, cap: 1500 },
    notes: "5% quarterly categories, $1,500 combined cap. Q3 2026: gas/EV, transit, live entertainment, United Way.",
  }),
  c({
    id: "chase-freedom",
    name: "Chase Freedom",
    short: "Freedom",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#1593d0",
    rotating: { type: "quarterly", calendar: "chase", rate: 5, cap: 1500 },
  }),
  c({
    id: "chase-ink-cash",
    name: "Ink Business Cash",
    short: "Ink Cash",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 0,
    aliases: ["ink cash", "ink business cash"],
    cpp: 1,
    cur: "cash",
    color: "#0b3d2e",
    rates: {
      office: { rate: 5, cap: 25000 },
      internet: { rate: 5, cap: 25000 },
      phone: { rate: 5, cap: 25000 },
      wireless: { rate: 5, cap: 25000 },
      gas: { rate: 2, cap: 25000 },
      dining: { rate: 2, cap: 25000 },
    },
    merchants: { staples: 5, "office-depot": 5 },
    dedicated: ["office", "staples", "office-depot"],
    specialist: ["office", "internet", "phone"],
    notes: "5% office supply stores and internet/cable/phone on first $25k combined per anniversary year. 3% FX fee.",
  }),
  c({
    id: "chase-ink-unlimited",
    name: "Ink Business Unlimited",
    short: "Ink Unlimited",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#145c45",
    base: 1.5,
    notes: "1.5% unlimited. 3% FX fee.",
  }),
  c({
    id: "chase-ink-preferred",
    name: "Ink Business Preferred",
    short: "CIP",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.8,
    cur: "UR",
    color: "#0a3328",
    rates: { travel: 3, shipping: 3, ads: 3, internet: 3, phone: 3, wireless: 3 },
    specialist: ["shipping", "ads"],
  }),
  c({
    id: "chase-ink-premier",
    name: "Ink Business Premier",
    short: "Ink Premier",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 195,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#08261e",
    base: 2.5,
    rates: { travel: 5 },
  }),
  c({
    id: "amazon-prime-visa",
    name: "Prime Visa",
    short: "Prime Visa",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    aliases: ["amazon prime visa", "amazon visa prime", "prime rewards visa"],
    cpp: 1,
    cur: "cash",
    color: "#232f3e",
    merchants: { amazon: 5, "whole-foods": 5 },
    dedicated: ["amazon"],
    specialist: ["amazon"],
    rates: { travel: 5, gas: 2, dining: 2, transit: 2, amazon: 5 },
    notes: "Unlimited 5% at Amazon.com, Amazon Fresh, Whole Foods, and Chase Travel with Prime. No FX fee.",
  }),
  c({
    id: "amazon-visa",
    name: "Amazon Visa",
    short: "Amazon Visa",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#37475a",
    merchants: { amazon: 3 },
    dedicated: ["amazon"],
    notes: "Non-Prime Amazon Visa: 3% Amazon.",
  }),
  c({
    id: "chase-united-explorer",
    name: "United Explorer",
    short: "Explorer",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "United",
    color: "#002244",
    cobrand: "united",
    merchants: { united: 2 },
    rates: { dining: 2, hotels: 2 },
  }),
  c({
    id: "chase-united-quest",
    name: "United Quest",
    short: "Quest",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 250,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "United",
    color: "#001a33",
    cobrand: "united",
    merchants: { united: 3 },
    rates: { dining: 3, hotels: 2 },
  }),
  c({
    id: "chase-united-club",
    name: "United Club Infinite",
    short: "United Club",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 695,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "United",
    color: "#001429",
    cobrand: "united",
    merchants: { united: 4 },
    rates: { dining: 2, travel: 2 },
    perks: ["lounge"],
  }),
  c({
    id: "chase-united-gateway",
    name: "United Gateway",
    short: "Gateway",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1.3,
    cur: "United",
    color: "#1a4a7a",
    cobrand: "united",
    merchants: { united: 2 },
  }),
  c({
    id: "chase-united-business",
    name: "United Business Card",
    short: "United Biz",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "United",
    color: "#002244",
    cobrand: "united",
    merchants: { united: 2 },
    rates: { dining: 2, gas: 2, office: 2 },
  }),
  c({
    id: "chase-southwest-plus",
    name: "Southwest Rapid Rewards Plus",
    short: "SW Plus",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 69,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "Southwest",
    color: "#304cb2",
    cobrand: "southwest",
    merchants: { southwest: 2 },
    rates: { transit: 2 },
  }),
  c({
    id: "chase-southwest-premier",
    name: "Southwest Rapid Rewards Premier",
    short: "SW Premier",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "Southwest",
    color: "#243a8c",
    cobrand: "southwest",
    merchants: { southwest: 3 },
  }),
  c({
    id: "chase-southwest-priority",
    name: "Southwest Rapid Rewards Priority",
    short: "SW Priority",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 149,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "Southwest",
    color: "#1b2d6e",
    cobrand: "southwest",
    merchants: { southwest: 3 },
  }),
  c({
    id: "chase-southwest-business",
    name: "Southwest Rapid Rewards Premier Business",
    short: "SW Biz",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.3,
    cur: "Southwest",
    color: "#243a8c",
    cobrand: "southwest",
    merchants: { southwest: 3 },
  }),
  c({
    id: "chase-ihg-premier",
    name: "IHG One Rewards Premier",
    short: "IHG Premier",
    issuer: "Chase",
    network: "mastercard",
    kind: "personal",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "IHG",
    color: "#d4a017",
    cobrand: "ihg",
    cobrandRate: 25,
    merchants: { ihg: 25 },
    dedicated: ["ihg"],
  }),
  c({
    id: "chase-ihg-premier-business",
    name: "IHG One Rewards Premier Business",
    short: "IHG Biz",
    issuer: "Chase",
    network: "mastercard",
    kind: "business",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "IHG",
    color: "#c49210",
    cobrand: "ihg",
    cobrandRate: 10,
    merchants: { ihg: 10 },
    dedicated: ["ihg"],
  }),
  c({
    id: "chase-marriott-boundless",
    name: "Marriott Bonvoy Boundless",
    short: "Boundless",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#8b1e3f",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
  }),
  c({
    id: "chase-marriott-bold",
    name: "Marriott Bonvoy Bold",
    short: "Bold",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 0.8,
    cur: "Marriott",
    color: "#a33a57",
    cobrand: "marriott",
    cobrandRate: 3,
    merchants: { marriott: 3 },
    dedicated: ["marriott"],
  }),
  c({
    id: "chase-world-of-hyatt",
    name: "World of Hyatt",
    short: "Hyatt",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.7,
    cur: "Hyatt",
    color: "#5b2c6f",
    cobrand: "hyatt",
    cobrandRate: 9,
    merchants: { hyatt: 9 },
    dedicated: ["hyatt"],
    rates: { dining: 2, transit: 2, gas: 2, ev: 2, fitness: 2 },
  }),
  c({
    id: "chase-aeroplan",
    name: "Aeroplan Credit Card",
    short: "Aeroplan",
    issuer: "Chase",
    network: "mastercard",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "Aeroplan",
    color: "#c8102e",
    rates: { dining: 3, travel: 3 },
  }),
  c({
    id: "chase-british-airways",
    name: "British Airways Visa Signature",
    short: "Avios",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "Avios",
    color: "#075aaa",
    rates: { travel: 3, dining: 2 },
  }),
  c({
    id: "chase-disney",
    name: "Disney® Visa",
    short: "Disney",
    issuer: "Chase",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#113ccf",
    merchants: {},
    notes: "Statement credits at Disney, not a category monster.",
  }),
  c({
    id: "citi-double-cash",
    name: "Citi Double Cash",
    short: "Double Cash",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#003b70",
    base: 2,
  }),
  c({
    id: "citi-custom-cash",
    name: "Citi Custom Cash",
    short: "Custom Cash",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#00539b",
    rates: {
      dining: { rate: 5, cap: 6000 },
      gas: { rate: 5, cap: 6000 },
      groceries: { rate: 5, cap: 6000 },
      travel: { rate: 5, cap: 6000 },
      transit: { rate: 5, cap: 6000 },
      drugstores: { rate: 5, cap: 6000 },
      home: { rate: 5, cap: 6000 },
      entertainment: { rate: 5, cap: 6000 },
    },
    notes: "5% on top eligible category each billing cycle, $500/month. App uses it as a flexible 5% specialist — still loses dedicated store cards.",
  }),
  c({
    id: "citi-strata-nofee",
    name: "Citi Strata",
    short: "Strata",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    aliases: ["citi strata card", "strata no fee", "strata $0"],
    cpp: 1.6,
    cur: "TY",
    color: "#4b6d9b",
    rates: { groceries: 3, gas: 3, ev: 3, transit: 3, streaming: 3 },
    notes: "No-annual-fee Strata. Unique id citi-strata-nofee vs Premier/Elite.",
  }),
  c({
    id: "citi-strata-premier",
    name: "Citi Strata Premier",
    short: "Strata Premier",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.7,
    cur: "TY",
    color: "#1f4e79",
    rates: { dining: 3, groceries: 3, gas: 3, ev: 3, flights: 3, hotels: 3 },
    specialist: ["travel"],
  }),
  c({
    id: "citi-strata-elite",
    name: "Citi Strata Elite",
    short: "Strata Elite",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 595,
    flags: ["no_fx_fee"],
    cpp: 1.85,
    cur: "TY",
    color: "#0d2c4a",
    rates: { hotels: 12, dining: 3, flights: 3, travel: 3 },
    perks: ["lounge"],
    specialist: ["hotels"],
    notes: "Elevated hotel earn through Citi Travel; not a Hilton cobrand.",
  }),
  c({
    id: "citi-costco-anywhere",
    name: "Costco Anywhere Visa",
    short: "Costco Visa",
    issuer: "Citi",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    aliases: ["costco citi", "costco anywhere", "costco visa"],
    cpp: 1,
    cur: "cash",
    color: "#e31837",
    merchants: { costco: 2, "costco-gas": 5 },
    dedicated: ["costco"],
    specialist: ["costco"],
    rates: { gas: { rate: 4, cap: 7000 }, ev: { rate: 4, cap: 7000 }, dining: 3, travel: 3, costco: 2 },
    notes: "Costco warehouses are Visa-only. 5% Costco gas / 4% other gas+EV first $7k combined, 3% restaurants and travel, 2% Costco.",
  }),
  c({
    id: "citi-dividend",
    name: "Citi Dividend",
    short: "Dividend",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#2e6eb5",
    rotating: { type: "quarterly", calendar: "citiDividend", rate: 5, cap: 6000 },
  }),
  c({
    id: "citi-rewards-plus",
    name: "Citi Rewards+",
    short: "Rewards+",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1.5,
    cur: "TY",
    color: "#3b6fa0",
    rates: { groceries: 2, gas: 2 },
    notes: "10% points back on first 100k points/year.",
  }),
  c({
    id: "citi-simplicity",
    name: "Citi Simplicity",
    short: "Simplicity",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 0,
    cur: "cash",
    color: "#5a7aa0",
    base: 0,
    notes: "No rewards. 0% APR tool, not a swipe earner.",
  }),
  c({
    id: "citi-aa-plat",
    name: "Citi AAdvantage Platinum Select",
    short: "AA Plat",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "AA",
    color: "#b61f2f",
    cobrand: "american-airlines",
    merchants: { "american-airlines": 2 },
    rates: { dining: 2, groceries: 2 },
  }),
  c({
    id: "citi-aa-exec",
    name: "Citi AAdvantage Executive",
    short: "AA Exec",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 595,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "AA",
    color: "#8e101c",
    cobrand: "american-airlines",
    merchants: { "american-airlines": 4 },
    perks: ["lounge"],
  }),
  c({
    id: "citi-aa-personal",
    name: "Citi / AAdvantage Mastercard",
    short: "AA Everyday",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1.4,
    cur: "AA",
    color: "#d32f3f",
    cobrand: "american-airlines",
    merchants: { "american-airlines": 2 },
  }),
  c({
    id: "citi-aa-business",
    name: "CitiBusiness AAdvantage Platinum Select",
    short: "AA Biz",
    issuer: "Citi",
    network: "mastercard",
    kind: "business",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "AA",
    color: "#b61f2f",
    cobrand: "american-airlines",
    merchants: { "american-airlines": 2 },
  }),
  c({
    id: "capital-one-venture-x",
    name: "Capital One Venture X",
    short: "Venture X",
    issuer: "Capital One",
    network: "visa",
    kind: "personal",
    fee: 395,
    flags: ["no_fx_fee"],
    cpp: 1.7,
    cur: "CapOne",
    color: "#0b1c2c",
    base: 2,
    rates: { travel: 10, hotels: 10, flights: 5 },
    perks: ["lounge"],
    specialist: ["travel"],
  }),
  c({
    id: "capital-one-venture",
    name: "Capital One Venture",
    short: "Venture",
    issuer: "Capital One",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.7,
    cur: "CapOne",
    color: "#12324a",
    base: 2,
    rates: { hotels: 5, rental: 5 },
  }),
  c({
    id: "capital-one-venture-one",
    name: "Capital One VentureOne",
    short: "VentureOne",
    issuer: "Capital One",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1.6,
    cur: "CapOne",
    color: "#1b4664",
    base: 1.25,
  }),
  c({
    id: "capital-one-savor",
    name: "Capital One Savor",
    short: "Savor",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#8b1a3a",
    rates: { dining: 3, entertainment: 3, streaming: 3, groceries: 3 },
    specialist: ["dining", "entertainment"],
  }),
  c({
    id: "capital-one-savorone",
    name: "Capital One SavorOne",
    short: "SavorOne",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#a83252",
    rates: { dining: 3, entertainment: 3, streaming: 3, groceries: 3 },
  }),
  c({
    id: "capital-one-savorone-student",
    name: "SavorOne Student",
    short: "SavorOne Student",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#c45c74",
    rates: { dining: 3, entertainment: 3, streaming: 3, groceries: 3 },
  }),
  c({
    id: "capital-one-quicksilver",
    name: "Capital One Quicksilver",
    short: "Quicksilver",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#c0c0c0",
    base: 1.5,
  }),
  c({
    id: "capital-one-quicksilver-one",
    name: "Capital One QuicksilverOne",
    short: "QSOne",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 39,
    cpp: 1,
    cur: "cash",
    color: "#9aa0a6",
    base: 1.5,
  }),
  c({
    id: "capital-one-spark-miles",
    name: "Spark Miles",
    short: "Spark Miles",
    issuer: "Capital One",
    network: "visa",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1.6,
    cur: "CapOne",
    color: "#1a1a2e",
    base: 2,
    rates: { hotels: 5, car_rental: 5 },
  }),
  c({
    id: "capital-one-spark-miles-select",
    name: "Spark Miles Select",
    short: "Spark Miles Select",
    issuer: "Capital One",
    network: "visa",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "CapOne",
    color: "#22223a",
    base: 1.5,
  }),
  c({
    id: "capital-one-spark-cash-plus",
    name: "Spark Cash Plus",
    short: "Spark Cash+",
    issuer: "Capital One",
    network: "mastercard",
    kind: "business",
    fee: 150,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#0d0d0d",
    base: 2,
  }),
  c({
    id: "capital-one-spark-cash-select",
    name: "Spark Cash Select",
    short: "Spark Select",
    issuer: "Capital One",
    network: "mastercard",
    kind: "business",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#333",
    base: 1.5,
  }),
  c({
    id: "capital-one-venture-x-business",
    name: "Capital One Venture X Business",
    short: "VX Biz",
    issuer: "Capital One",
    network: "visa",
    kind: "business",
    fee: 395,
    flags: ["no_fx_fee"],
    cpp: 1.7,
    cur: "CapOne",
    color: "#0b1c2c",
    base: 2,
    rates: { travel: 10, flights: 5 },
    perks: ["lounge"],
  }),
  c({
    id: "capital-one-walmart-rewards",
    name: "Walmart Rewards Card",
    short: "Walmart",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0071ce",
    merchants: { walmart: 5 },
    dedicated: ["walmart"],
    rates: { walmart: 5 },
    notes: "Higher Walmart earn with Walmart+ in some offers; 5% is the dedicated-store case.",
  }),
  c({
    id: "discover-it",
    name: "Discover it Cash Back",
    short: "Discover it",
    issuer: "Discover",
    network: "discover",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#ff6000",
    rotating: { type: "quarterly", calendar: "discover", rate: 5, cap: 1500 },
    notes: "Q3 2026: gas, transportation, drugstores. Activate each quarter. First-year Cashback Match.",
  }),
  c({
    id: "discover-it-miles",
    name: "Discover it Miles",
    short: "Discover Miles",
    issuer: "Discover",
    network: "discover",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#e05500",
    base: 1.5,
  }),
  c({
    id: "discover-it-chrome",
    name: "Discover it chrome",
    short: "Discover chrome",
    issuer: "Discover",
    network: "discover",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#f4c431",
    rates: { gas: 2, dining: 2 },
  }),
  c({
    id: "discover-it-student",
    name: "Discover it Student Cash Back",
    short: "Discover Student",
    issuer: "Discover",
    network: "discover",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#ff7a26",
    rotating: { type: "quarterly", calendar: "discover", rate: 5, cap: 1500 },
  }),
  c({
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash",
    short: "Active Cash",
    issuer: "Wells Fargo",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#d71e28",
    base: 2,
  }),
  c({
    id: "wells-fargo-autograph",
    name: "Wells Fargo Autograph",
    short: "Autograph",
    issuer: "Wells Fargo",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "WF",
    color: "#b5121b",
    rates: { dining: 3, travel: 3, gas: 3, ev: 3, transit: 3, streaming: 3, phone: 3 },
  }),
  c({
    id: "wells-fargo-autograph-journey",
    name: "Wells Fargo Autograph Journey",
    short: "Autograph Journey",
    issuer: "Wells Fargo",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.6,
    cur: "WF",
    color: "#8e0e16",
    rates: { hotels: 5, travel: 4, dining: 3 },
  }),
  c({
    id: "bilt",
    name: "Bilt Mastercard",
    short: "Bilt",
    issuer: "Wells Fargo",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    aliases: ["bilt rewards", "bilt card"],
    cpp: 1.8,
    cur: "Bilt",
    color: "#111111",
    rentEligible: true,
    rates: { rent: 1, dining: 3, travel: 2, flights: 2, hotels: 2 },
    dedicated: ["rent"],
    specialist: ["rent"],
    notes: "1x on rent (up to 100k points/year) with no landlord fee. Only mainstream card that belongs on rent.",
  }),
  c({
    id: "wells-fargo-reflect",
    name: "Wells Fargo Reflect",
    short: "Reflect",
    issuer: "Wells Fargo",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 0,
    cur: "cash",
    color: "#666",
    base: 0,
    notes: "0% APR card, not a rewards earner.",
  }),
  c({
    id: "apple-card",
    name: "Apple Card",
    short: "Apple Card",
    issuer: "Goldman Sachs / Apple",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    aliases: ["apple card", "daily cash"],
    cpp: 1,
    cur: "Daily Cash",
    color: "#f5f5f7",
    merchants: { apple: 3 },
    dedicated: ["apple"],
    rates: { apple: 3 },
    base: 2,
    notes: "3% Daily Cash at Apple, 2% with Apple Pay, 1% when you use the physical card. No foreign transaction fee. Modeled as 2% everyday (Apple Pay) and 3% at Apple.",
  }),
  c({
    id: "target-redcard",
    name: "Target Circle Card (RedCard)",
    short: "RedCard",
    issuer: "TD Bank",
    network: "visa",
    kind: "personal",
    fee: 0,
    aliases: ["target redcard", "target circle card", "redcard", "target debit"],
    cpp: 1,
    cur: "cash",
    color: "#cc0000",
    merchants: { target: 5 },
    dedicated: ["target"],
    specialist: ["target"],
    rates: { target: 5 },
    notes: "5% off most Target purchases in-store and at Target.com.",
  }),
  c({
    id: "usbank-cash-plus",
    name: "U.S. Bank Cash+",
    short: "Cash+",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0c2074",
    rates: { electronics: { rate: 5, cap: 8000 }, dining: { rate: 5, cap: 8000 }, home: { rate: 5, cap: 8000 } },
    notes: "Choose two 5% categories each quarter ($2,000 each). Electronics is a popular pick — still usually loses to Business Gold's 4x MR + warranty on electronics.",
  }),
  c({
    id: "usbank-altitude-go",
    name: "U.S. Bank Altitude Go",
    short: "Altitude Go",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1.5,
    cur: "USB",
    color: "#1a2f8a",
    rates: { dining: 4, groceries: 2, gas: 2, streaming: 2 },
  }),
  c({
    id: "usbank-altitude-connect",
    name: "U.S. Bank Altitude Connect",
    short: "Altitude Connect",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "USB",
    color: "#243a9c",
    rates: { travel: 4, gas: 2, ev: 2, groceries: 2, streaming: 2 },
  }),
  c({
    id: "usbank-altitude-reserve",
    name: "U.S. Bank Altitude Reserve",
    short: "Altitude Reserve",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "personal",
    fee: 400,
    flags: ["no_fx_fee"],
    cpp: 1.8,
    cur: "USB",
    color: "#071448",
    base: 3,
    rates: { travel: 3 },
    notes: "3x when paid with mobile wallet. Strong everyday Apple Pay / Google Pay card.",
  }),
  c({
    id: "usbank-shopper-cash",
    name: "U.S. Bank Shopper Cash Rewards",
    short: "Shopper Cash",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "personal",
    fee: 95,
    cpp: 1,
    cur: "cash",
    color: "#13257c",
    rates: { groceries: { rate: 6, cap: 1500 }, online: { rate: 3, cap: 1500 } },
  }),
  c({
    id: "usbank-business-triple-cash",
    name: "U.S. Bank Business Triple Cash",
    short: "USB Triple Cash",
    issuer: "U.S. Bank",
    network: "visa",
    kind: "business",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0c2074",
    rates: { gas: 3, ev: 3, office: 3, dining: 3, cell: 3, travel: 3 },
  }),
  c({
    id: "boa-customized-cash",
    name: "Bank of America Customized Cash",
    short: "BoA Customized",
    issuer: "Bank of America",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#e31837",
    rates: { gas: 3, dining: 3, travel: 3, drugstores: 3, home: 3 },
    notes: "3% in one chosen category (up to 5.25% with Preferred Rewards).",
  }),
  c({
    id: "boa-premium-rewards",
    name: "Bank of America Premium Rewards",
    short: "BoA Premium",
    issuer: "Bank of America",
    network: "visa",
    kind: "personal",
    fee: 95,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "BoA",
    color: "#c41230",
    rates: { travel: 2, dining: 2 },
    base: 1.5,
  }),
  c({
    id: "boa-premium-rewards-elite",
    name: "Bank of America Premium Rewards Elite",
    short: "BoA Elite",
    issuer: "Bank of America",
    network: "visa",
    kind: "personal",
    fee: 550,
    flags: ["no_fx_fee"],
    cpp: 1.6,
    cur: "BoA",
    color: "#8e0d22",
    rates: { travel: 2, dining: 2 },
    base: 1.5,
    perks: ["lounge"],
  }),
  c({
    id: "boa-travel-rewards",
    name: "Bank of America Travel Rewards",
    short: "BoA Travel",
    issuer: "Bank of America",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#f04b4b",
    base: 1.5,
  }),
  c({
    id: "boa-unlimited-cash",
    name: "Bank of America Unlimited Cash",
    short: "BoA Unlimited",
    issuer: "Bank of America",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#ff6b6b",
    base: 1.5,
  }),
  c({
    id: "fidelity-rewards-visa",
    name: "Fidelity® Rewards Visa",
    short: "Fidelity",
    issuer: "Fidelity / Elan",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#3c7800",
    base: 2,
  }),
  c({
    id: "sofi-credit-card",
    name: "SoFi Credit Card",
    short: "SoFi",
    issuer: "SoFi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#0176ff",
    base: 2,
  }),
  c({
    id: "paypal-cashback",
    name: "PayPal Cashback Mastercard",
    short: "PayPal",
    issuer: "Synchrony",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#003087",
    base: 3,
    notes: "3% when you check out with PayPal, 2% in store, 1% otherwise. Modeled as 3% online-ish base; dedicated store cards still win.",
  }),
  c({
    id: "penfed-power-cash",
    name: "PenFed Power Cash Rewards",
    short: "PenFed Power",
    issuer: "PenFed",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#0b3d91",
    base: 2,
  }),
  c({
    id: "penfed-platinum-rewards",
    name: "PenFed Platinum Rewards",
    short: "PenFed Platinum",
    issuer: "PenFed",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1.4,
    cur: "PenFed",
    color: "#092f70",
    rates: { gas: 5, ev: 5 },
    specialist: ["gas"],
  }),
  c({
    id: "navy-federal-more-rewards",
    name: "Navy Federal More Rewards",
    short: "NFCU More",
    issuer: "Navy Federal",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#002f6c",
    rates: { dining: 3, gas: 3, groceries: 3 },
  }),
  c({
    id: "navy-federal-flagship",
    name: "Navy Federal Flagship",
    short: "Flagship",
    issuer: "Navy Federal",
    network: "visa",
    kind: "personal",
    fee: 49,
    flags: ["no_fx_fee"],
    cpp: 1.5,
    cur: "NFCU",
    color: "#001e46",
    base: 2,
    rates: { travel: 3 },
  }),
  c({
    id: "barclays-aviator-red",
    name: "AAdvantage Aviator Red",
    short: "Aviator Red",
    issuer: "Barclays",
    network: "mastercard",
    kind: "personal",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "AA",
    color: "#c41230",
    cobrand: "american-airlines",
    merchants: { "american-airlines": 2 },
  }),
  c({
    id: "barclays-jetblue-plus",
    name: "JetBlue Plus",
    short: "JetBlue Plus",
    issuer: "Barclays",
    network: "mastercard",
    kind: "personal",
    fee: 99,
    flags: ["no_fx_fee"],
    cpp: 1.4,
    cur: "JetBlue",
    color: "#00205b",
    cobrand: "jetblue",
    merchants: { jetblue: 6 },
    rates: { dining: 2, groceries: 2 },
  }),
  c({
    id: "barclays-wyndham-earner-plus",
    name: "Wyndham Rewards Earner Plus",
    short: "Wyndham Plus",
    issuer: "Barclays",
    network: "mastercard",
    kind: "personal",
    fee: 75,
    flags: ["no_fx_fee"],
    cpp: 0.7,
    cur: "Wyndham",
    color: "#1b365d",
    cobrand: "wyndham",
    cobrandRate: 6,
    merchants: { wyndham: 6 },
    dedicated: ["wyndham"],
    rates: { gas: 4, groceries: 4, dining: 3, travel: 2 },
  }),
  c({
    id: "verizon-visa",
    name: "Verizon Visa",
    short: "Verizon Visa",
    issuer: "Synchrony",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#cd040b",
    merchants: { verizon: 4 },
    dedicated: ["verizon"],
    rates: { dining: 3, groceries: 3, gas: 3 },
  }),
  c({
    id: "sams-club-mastercard",
    name: "Sam's Club Mastercard",
    short: "Sam's Club",
    issuer: "Synchrony",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0067a0",
    merchants: { "sams-club": 5 },
    dedicated: ["sams-club", "wholesale"],
    rates: { gas: { rate: 5, cap: 6000 }, dining: 3, travel: 1, wholesale: 5 },
  }),
  c({
    id: "robinhood-gold",
    name: "Robinhood Gold Card",
    short: "Robinhood Gold",
    issuer: "Robinhood",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#00c805",
    base: 3,
    notes: "3% on everything with Robinhood Gold. Strong flat-rate; dedicated 5% store cards still win those merchants.",
  }),
  c({
    id: "home-depot-card",
    name: "Home Depot Consumer Card",
    short: "Home Depot",
    issuer: "Citi",
    network: "store",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#f96302",
    merchants: { "home-depot": 5 },
    dedicated: ["home-depot", "home"],
    specialist: ["home"],
  }),
  c({
    id: "lowes-card",
    name: "MyLowe's Rewards Card",
    short: "Lowe's",
    issuer: "Synchrony",
    network: "store",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0474bc",
    merchants: { lowes: 5 },
    dedicated: ["lowes", "home"],
  }),
  c({
    id: "gm-rewards",
    name: "GM Rewards Mastercard",
    short: "GM Rewards",
    issuer: "Capital One",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#003c71",
    base: 1,
    notes: "Earnings toward GM vehicles, not general cash. Weak as a general swipe card.",
  }),
  c({
    id: "aaa-daily-advantage",
    name: "AAA Daily Advantage",
    short: "AAA Daily",
    issuer: "Citi",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#1e4d8c",
    rates: { groceries: 5, gas: 3, wholesale: 3 },
    specialist: ["groceries"],
  }),
  c({
    id: "alliant-cashback",
    name: "Alliant Cashback Visa Signature",
    short: "Alliant",
    issuer: "Alliant CU",
    network: "visa",
    kind: "personal",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#6e2c91",
    base: 2.5,
    notes: "2.5% with qualifying Alliant relationship; otherwise 1.5%.",
  }),
  c({
    id: "usaa-rewards",
    name: "USAA Rewards American Express",
    short: "USAA Amex",
    issuer: "USAA",
    network: "amex",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#003366",
    rates: { gas: 3, groceries: 3, dining: 2 },
  }),
  c({
    id: "elan-max-cash",
    name: "Elan Max Cash Preferred",
    short: "Elan Max Cash",
    issuer: "Elan",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#0055a5",
    rates: { dining: { rate: 5, cap: 8000 }, gas: { rate: 5, cap: 8000 }, groceries: { rate: 5, cap: 8000 } },
    notes: "Pick two 5% categories each quarter, like U.S. Bank Cash+.",
  }),
  c({
    id: "pnc-cash-unlimited",
    name: "PNC Cash Unlimited",
    short: "PNC Unlimited",
    issuer: "PNC",
    network: "visa",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#f48024",
    base: 2,
  }),
  c({
    id: "td-first-class",
    name: "TD First Class Visa",
    short: "TD First Class",
    issuer: "TD Bank",
    network: "visa",
    kind: "personal",
    fee: 89,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#34a853",
    rates: { travel: 3 },
    base: 2,
  }),
  c({
    id: "amazon-store",
    name: "Amazon Store Card",
    short: "Amazon Store",
    issuer: "Synchrony",
    network: "store",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#ff9900",
    merchants: { amazon: 5 },
    dedicated: ["amazon"],
    notes: "5% Amazon with Prime, but Amazon-only. Prime Visa is the everyday pick because it works everywhere Visa is taken.",
  }),
  c({
    id: "brex",
    name: "Brex Card",
    short: "Brex",
    issuer: "Brex",
    network: "mastercard",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#ff5a1f",
    rates: { travel: 4, dining: 3, rideshare: 3 },
    base: 1,
  }),
  c({
    id: "ramp",
    name: "Ramp Card",
    short: "Ramp",
    issuer: "Ramp",
    network: "visa",
    kind: "business",
    fee: 0,
    flags: ["no_fx_fee"],
    cpp: 1,
    cur: "cash",
    color: "#1a1a1a",
    base: 1.5,
  }),
  c({
    id: "amex-hilton-aspire-business",
    name: "Hilton Honors Aspire Business",
    short: "Aspire Biz",
    issuer: "American Express",
    network: "amex",
    kind: "business",
    fee: 550,
    flags: ["no_fx_fee"],
    cpp: 0.5,
    cur: "Hilton",
    color: "#0f2748",
    cobrand: "hilton",
    cobrandRate: 14,
    merchants: { hilton: 14 },
    dedicated: ["hilton"],
    specialist: ["hotels"],
  }),
  c({
    id: "chase-marriott-business",
    name: "Marriott Bonvoy Business",
    short: "Bonvoy Chase Biz",
    issuer: "Chase",
    network: "visa",
    kind: "business",
    fee: 125,
    flags: ["no_fx_fee"],
    cpp: 0.8,
    cur: "Marriott",
    color: "#8b1e3f",
    cobrand: "marriott",
    cobrandRate: 6,
    merchants: { marriott: 6 },
    dedicated: ["marriott"],
  }),
  c({
    id: "citi-custom-cash-2",
    name: "Citi Custom Cash (2nd)",
    short: "Custom Cash 2",
    issuer: "Citi",
    network: "mastercard",
    kind: "personal",
    fee: 0,
    cpp: 1,
    cur: "cash",
    color: "#2266aa",
    notes: "Some households hold two Custom Cash cards for two 5% buckets. Same product, unique id.",
    rates: { gas: { rate: 5, cap: 6000 } },
  }),
];

export function getCard(id, catalog = CARDS) {
  return catalog.find((card) => card.id === id) || null;
}

export function searchCatalog(query, catalog = CARDS) {
  const q = String(query || "")
    .trim()
    .toLowerCase();
  if (!q) return catalog;
  return catalog.filter((card) => {
    const blob = [card.id, card.name, card.short, card.issuer, ...(card.aliases || [])].join(" ").toLowerCase();
    return blob.includes(q);
  });
}

export function aliasCard(query, catalog = CARDS) {
  const hits = searchCatalog(query, catalog);
  return hits[0] || null;
}

export function categoriesForMode(mode) {
  return CATEGORIES.filter((c) => c.modes.includes(mode));
}
